# Generated by Django 4.2.1 on 2023-05-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='permalink',
            new_name='url',
        ),
    ]
