# Generated by Django 4.2.1 on 2023-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_permalink_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
