# Generated by Django 4.2.1 on 2023-06-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tags_post_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
